version: "3.4"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_homepage
    volumes:
      - ./static:/static/
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    expose:
      - 80
    networks:
        - pi
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homepage.rule=Path(`/`) || Path(`/robots.txt`)'
      - 'traefik.http.routers.homepage.tls'
      - 'traefik.http.routers.homepagenotls.rule=Path(`/`) || Path(`/robots.txt`)'
networks:
    pi:
      external: true
