version: "3.4"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_homepage
    volumes:
      - ./static:/static/
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    expose:
      - 80
    networks:
        - pi
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homepage.rule=Path(`/`)
      - 'traefik.http.routers.homepage.tls'
      - 'traefik.http.routers.homepagenotls.rule=Path(`/`)
      - 'traefik.http.middlewares.homepage-headers.headers.customResponseHeaders.X-Robots-Tag=noindex'
      - 'traefik.http.routers.homepage.middlewares=homepage-headers'
      - 'traefik.http.routers.homepagenotls.middlewares=homepage-headers'
networks:
    pi:
      external: true
